# Generated by Django 5.2.4 on 2025-07-08 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_update_at_post_updated_at_alter_post_author_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
